// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt96kPX_MSPuqQboKuAdAPLukgIpM6peA',
    appId: '1:750198742746:web:e8f2ece6c9e705d7c18fe3',
    messagingSenderId: '750198742746',
    projectId: 'well-link-8592e',
    authDomain: 'well-link-8592e.firebaseapp.com',
    storageBucket: 'well-link-8592e.firebasestorage.app',
    measurementId: 'G-3HTFYXZ3QN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFB89xladlgsVea1zf_9aucM9yC6OOYK8',
    appId: '1:750198742746:android:5c9cbdc8c410f2e4c18fe3',
    messagingSenderId: '750198742746',
    projectId: 'well-link-8592e',
    storageBucket: 'well-link-8592e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ9tyWGeR3jeXXHiSmrygHXgZ-0e-1N0U',
    appId: '1:750198742746:ios:2aba04a358a97691c18fe3',
    messagingSenderId: '750198742746',
    projectId: 'well-link-8592e',
    storageBucket: 'well-link-8592e.firebasestorage.app',
    iosBundleId: 'com.example.welllink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ9tyWGeR3jeXXHiSmrygHXgZ-0e-1N0U',
    appId: '1:750198742746:ios:2aba04a358a97691c18fe3',
    messagingSenderId: '750198742746',
    projectId: 'well-link-8592e',
    storageBucket: 'well-link-8592e.firebasestorage.app',
    iosBundleId: 'com.example.welllink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt96kPX_MSPuqQboKuAdAPLukgIpM6peA',
    appId: '1:750198742746:web:7ea1ff2930ef0365c18fe3',
    messagingSenderId: '750198742746',
    projectId: 'well-link-8592e',
    authDomain: 'well-link-8592e.firebaseapp.com',
    storageBucket: 'well-link-8592e.firebasestorage.app',
    measurementId: 'G-73NKMSN8GZ',
  );
}
